### ISSUE TITLE
Implementar accions de botons

### ISSUE THREAD

**Issue by mguellsegarra** [gisce/react-ooui#67]
- [x] Implementar botons de tipus workflow https://github.com/gisce/react-ooui/issues/68
- [x] Implementar botons de tipus object https://github.com/gisce/react-ooui/issues/69
- [x] Implementar botons de tipus action https://github.com/gisce/react-ooui/issues/70
