### ISSUE TITLE
Implementar botons de tipus action

### ISSUE THREAD

**Issue by mguellsegarra** [gisce/react-ooui#70]
- [x] [Botons action: ir.actions.act_window #78](https://github.com/gisce/react-ooui/issues/78)
- [x] [Botons action: ir.actions.server #79](https://github.com/gisce/react-ooui/issues/79)
- [x] [Botons action: ir.actions.wizard #80](https://github.com/gisce/react-ooui/issues/80)
- [x] [Botons action: ir.actions.report.custom #81](https://github.com/gisce/react-ooui/issues/81)
- [x] [Botons action: ir.actions.report.xml #82](https://github.com/gisce/react-ooui/issues/82)
